import { mkdir, readFile, writeFile } from 'node:fs/promises'
import ts from 'typescript'

const source = await readFile(new URL('../src/client/index.ts', import.meta.url), 'utf8')
const output = ts.transpileModule(source, {
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, isolatedModules: true },
  fileName: 'index.ts', reportDiagnostics: true,
})
const errors = output.diagnostics?.filter(row => row.category === ts.DiagnosticCategory.Error) ?? []
if (errors.length > 0) throw new Error(ts.formatDiagnosticsWithColorAndContext(errors, {
  getCanonicalFileName: value => value, getCurrentDirectory: () => process.cwd(), getNewLine: () => '\n',
}))
await mkdir(new URL('../lib/', import.meta.url), { recursive: true })
const body = output.outputText.split('\n').map(line => `    ${line}`).join('\n')
await writeFile(new URL('../lib/client.js', import.meta.url), `// Generated by @xiaoshe/coding-workbench.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/coding-workbench',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${body}\n    return module.exports\n  },\n})\n`, 'utf8')
