import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(packageRoot, 'src/client/index.ts')
const outputPath = resolve(packageRoot, 'lib/client.js')
const result = ts.transpileModule(await readFile(sourcePath, 'utf8'), {
  fileName: sourcePath,
  reportDiagnostics: true,
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, strict: true },
})
if ((result.diagnostics ?? []).length > 0) {
  throw new Error(ts.formatDiagnosticsWithColorAndContext(result.diagnostics ?? [], { getCanonicalFileName: value => value, getCurrentDirectory: () => packageRoot, getNewLine: () => '\n' }))
}
const body = result.outputText.split('\n').map(line => `    ${line}`).join('\n')
await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `// Generated by @xiaoshe/plugin-governance.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/plugin-governance',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${body}\n    return module.exports\n  },\n})\n`)
