import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(packageRoot, 'src/client/index.ts')
const rawSource = await readFile(sourcePath, 'utf8')
const result = ts.transpileModule(rawSource, {
  fileName: sourcePath,
  reportDiagnostics: true,
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, strict: true },
})
const diagnostics = result.diagnostics ?? []
if (diagnostics.length > 0) {
  throw new Error(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: value => value,
    getCurrentDirectory: () => packageRoot,
    getNewLine: () => '\n',
  }))
}
const indented = result.outputText.split('\n').map(line => `    ${line}`).join('\n')
const output = resolve(packageRoot, 'lib/client.js')
await mkdir(dirname(output), { recursive: true })
await writeFile(output, `// Generated by @xiaoshe/migration-recovery.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/migration-recovery',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${indented}\n    return module.exports\n  },\n})\n`, 'utf8')
