import { describe, expect, it } from 'vitest'
import { resolve } from 'node:path'
import { ACTION_TOOL_NAMES, createToolDefinitions, type BridgeRequester } from '../src/tools.js'
import type { JsonValue, ResolvedConfig } from '../src/types.js'

class FakeBridge implements BridgeRequester {
  readonly calls: Array<{ method: string; params: JsonValue }> = []

  async request(method: string, params: JsonValue): Promise<JsonValue> {
    this.calls.push({ method, params })
    return { method, params }
  }
}

const enabled: ResolvedConfig = {
  xiaosheRoot: resolve('runtime/xiaoshe-legacy'),
  pythonExecutable: process.platform === 'win32' ? 'python' : 'python3',
  actionsEnabled: true,
  requestTimeoutMs: 60_000,
}

const observation: JsonValue = {
  status: 'observed',
  viewport_id: 'viewport-after',
  parent_viewport_id: '',
  image_path: '/private/tmp/xiaoshe/screen.png',
  sha256: 'a'.repeat(64),
  captured_at: '2026-08-20T00:00:00Z',
  pixel_size: { width: 2000, height: 1200 },
  logical_size: { width: 1000, height: 600 },
  origin: { x: 0, y: 0 },
  scale: 2,
  elements: [{ id: 'e1', ref: 'button', role: 'button', name: '确认', x: 1, y: 2, w: 3, h: 4 }],
  warnings: [],
}

function tool(name: string, bridge = new FakeBridge()) {
  const found = createToolDefinitions(bridge, enabled).find(item => item.name === name)
  if (found === undefined) throw new Error(`missing tool ${name}`)
  return { found, bridge }
}

describe('Xiaoshe DSH tools', () => {
  it('registers window discovery and approved focus with the desktop tool family', () => {
    const names = createToolDefinitions(new FakeBridge(), enabled).map(item => item.name)
    expect(names).toEqual([
      'screen_observe', 'screen_zoom', 'screen_verify', 'screen_list_windows',
      'screen_click', 'screen_type', 'screen_press', 'screen_focus_window',
    ])
    expect([...ACTION_TOOL_NAMES].sort()).toEqual(['screen_click', 'screen_focus_window', 'screen_press', 'screen_type'])
  })

  it('removes action definitions completely when deployment disables them', () => {
    const names = createToolDefinitions(new FakeBridge(), { ...enabled, actionsEnabled: false }).map(item => item.name)
    expect(names).toEqual(['screen_observe', 'screen_zoom', 'screen_verify', 'screen_list_windows'])
  })

  it('uses an ephemeral window id plus exact reviewed title for focus', async () => {
    const { found, bridge } = tool('screen_focus_window')
    await found.execute({ window_id: 'w-123', title: 'Xiaoshe Isolated Window' }, { signal: new AbortController().signal })
    expect(bridge.calls).toEqual([{ method: 'focus_window', params: { window_id: 'w-123', title: 'Xiaoshe Isolated Window' } }])
  })

  it('maps observe defaults to the narrow RPC protocol', async () => {
    const { found, bridge } = tool('screen_observe')
    await found.execute({}, { signal: new AbortController().signal })
    expect(bridge.calls).toEqual([{ method: 'observe', params: { include_elements: true, max_elements: 40 } }])
  })

  it('requires click element mode or coordinate mode, never both', async () => {
    const { found, bridge } = tool('screen_click')
    const signal = new AbortController().signal
    await expect(found.execute({ viewport_id: 'v1' }, { signal })).rejects.toThrow(/exactly one target/)
    await expect(found.execute({ viewport_id: 'v1', element_id: 'button', image_x: 1, image_y: 2 }, { signal }))
      .rejects.toThrow(/exactly one target/)
    await found.execute({ viewport_id: 'v1', image_x: 10, image_y: 20 }, { signal })
    expect(bridge.calls.at(-1)).toEqual({
      method: 'click',
      params: { viewport_id: 'v1', image_x: 10, image_y: 20 },
    })
  })

  it('does not include typed text in the presentation result generated by the bridge wrapper', async () => {
    const { found, bridge } = tool('screen_type')
    await found.execute({ viewport_id: 'v1', text: 'sensitive fixture' }, { signal: new AbortController().signal })
    expect(bridge.calls).toEqual([{
      method: 'type_text',
      params: { viewport_id: 'v1', text: 'sensitive fixture' },
    }])
  })

  it('redacts typed text from the durable call presentation', () => {
    const { found } = tool('screen_type')
    const view = found.presentCall?.({ viewport_id: 'v1', text: 'sensitive fixture' })
    expect(JSON.stringify(view)).not.toContain('sensitive fixture')
    expect(view).toMatchObject({
      title: '向桌面输入文本',
      rawInput: { viewport_id: 'v1', text_length: 17, text: '[已隐藏]' },
    })
  })

  it('projects replayable before-and-after evidence for action cards', () => {
    const { found } = tool('screen_click')
    const value: JsonValue = {
      status: 'completed',
      action: 'click',
      message: 'done',
      changed: true,
      target: '确认',
      before_viewport_id: 'viewport-before',
      after: observation,
      added: [],
      removed: [{ id: 'e0', ref: 'old', role: 'button', name: '旧按钮', x: 1, y: 2, w: 3, h: 4 }],
    }
    const meta = found.output.presentationMeta?.({}, value)
    if (meta === undefined) throw new Error('action tool did not project presentation metadata')
    expect(meta).toEqual({
      status: 'completed',
      changed: true,
      target: '确认',
      before_viewport_id: 'viewport-before',
      after_viewport_id: 'viewport-after',
      added_count: 0,
      removed_count: 1,
    })
    expect(found.presentResult?.({}, { content: [], isError: false, meta })).toEqual({
      card: 'generic',
      title: '点击已完成 · 界面有变化',
      content: [{
        type: 'text',
        text: '操作前 viewport-before\n操作后 viewport-after\n新增元素 0 个 · 移除元素 1 个\n目标 确认',
      }],
    })
  })

  it('falls back safely when replay metadata is absent or malformed', () => {
    const { found } = tool('screen_verify')
    expect(found.presentResult?.({}, { content: [], isError: false })).toBeUndefined()
    expect(found.presentResult?.({}, { content: [], isError: false, meta: { changed: true } })).toBeUndefined()
    expect(found.presentResult?.({}, { content: [], isError: true, meta: {} })).toBeUndefined()
  })
})
