import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(packageRoot, 'src/client/index.ts')
const outputPath = resolve(packageRoot, 'lib/client.js')

const source = await readFile(sourcePath, 'utf8')
const result = ts.transpileModule(source, {
  fileName: sourcePath,
  reportDiagnostics: true,
  compilerOptions: {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.CommonJS,
    strict: true,
  },
})

const diagnostics = result.diagnostics ?? []
if (diagnostics.length > 0) {
  const message = ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: value => value,
    getCurrentDirectory: () => packageRoot,
    getNewLine: () => '\n',
  })
  throw new Error(`Client transpilation failed:\n${message}`)
}

const artifact = `// Generated by @xiaoshe/native-shell.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/native-shell',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${indent(result.outputText, 4)}\n    return module.exports\n  },\n})\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, artifact, 'utf8')

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces)
  return value.split('\n').map(line => `${prefix}${line}`).join('\n')
}
