import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const contractSource = resolve(packageRoot, '../runtime-contract/src/index.ts')
const result = await build({
  entryPoints: [resolve(packageRoot, 'src/client/index.ts')], bundle: true, write: false,
  platform: 'browser', format: 'cjs', target: 'es2022', logLevel: 'silent',
  plugins: [{ name: 'xiaoshe-runtime-contract-source', setup(api) {
    api.onResolve({ filter: /^@xiaoshe\/runtime-contract$/ }, () => ({ path: contractSource }))
  } }],
})
const body = result.outputFiles[0]?.text
if (body === undefined) throw new Error('provider readiness Client build produced no artifact')
const indented = body.split('\n').map(line => `    ${line}`).join('\n')
const output = resolve(packageRoot, 'lib/client.js')
await mkdir(dirname(output), { recursive: true })
await writeFile(output, `// Generated by @xiaoshe/provider-readiness.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/provider-readiness',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${indented}\n    return module.exports\n  },\n})\n`, 'utf8')
