import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(packageRoot, 'src/client/index.ts')
const outputPath = resolveOutputPath(process.argv.slice(2))
const stylePaths = [
  'tokens.css',
  'base.css',
  'components.css',
  'panels.css',
  'observatory.css',
].map(name => resolve(packageRoot, 'ui/styles', name))
stylePaths.push(resolve(packageRoot, 'src/client/adapted.css'))
const [rawSource, ...styleParts] = await Promise.all([
  readFile(sourcePath, 'utf8'),
  ...stylePaths.map(path => readFile(path, 'utf8')),
])
const heritageCss = styleParts.join('\n\n')
const marker = "'__XIAOSHE_LEGACY_ADAPTED_CSS__'"
if (rawSource.split(marker).length !== 2) {
  throw new Error('Expected exactly one legacy-adapted CSS marker in the Client source')
}
const source = rawSource.replace(marker, JSON.stringify(heritageCss))
const result = ts.transpileModule(source, {
  fileName: sourcePath,
  reportDiagnostics: true,
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, strict: true },
})

const diagnostics = result.diagnostics ?? []
if (diagnostics.length > 0) {
  const message = ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: value => value,
    getCurrentDirectory: () => packageRoot,
    getNewLine: () => '\n',
  })
  throw new Error(`Client transpilation failed:\n${message}`)
}

const artifact = `// Generated by @xiaoshe/native-shell-legacy-adapted.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/native-shell-legacy-adapted',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${indent(result.outputText, 4)}\n    return module.exports\n  },\n})\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, artifact, 'utf8')

function resolveOutputPath(args) {
  if (args.length === 0) return resolve(packageRoot, 'lib/client.js')
  if (args.length !== 2 || args[0] !== '--output' || args[1].trim() === '') {
    throw new Error('Usage: build-client.mjs [--output <client.js path>]')
  }
  return resolve(packageRoot, args[1])
}

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces)
  return value.split('\n').map(line => `${prefix}${line}`).join('\n')
}
