/* Task v2 REST 客户端：响应保持服务端事实形状，409 由调用层显示可操作回执。 */
import * as net from "../net.js";

export const inbox = () => net.get("/api/v2/inbox");
export const projects = () => net.get("/api/v2/projects");
export const createProject = (name, root = undefined) => net.post("/api/v2/projects", root ? { name, root } : { name });
export const createTask = (body) => net.post("/api/v2/tasks", body);
export const task = (id, after = 0) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}?events_after=${after}`);
export const updateTask = (id, body) => net.patch(`/api/v2/tasks/${encodeURIComponent(id)}`, body);
export const transition = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/transition`, body);
export const plans = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/plans`);
export const proposePlan = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/plans`, body);
export const reviewPlan = (id, revision, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/plans/${revision}/review`, body);
export const currentChangeset = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/changesets/current`);
export const toolCandidates = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/tool-proposals`);
export const proposeTool = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/tool-proposals`, body);
export const captureChangeset = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/changesets`, body);
export const reviewArtifact = (taskId, changesetId, key) => net.get(`/api/v2/tasks/${encodeURIComponent(taskId)}/changesets/${encodeURIComponent(changesetId)}/artifacts/${encodeURIComponent(key)}`);
export const submitReview = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/reviews`, body);
export const verificationProfiles = (projectId) => net.get(`/api/v2/projects/${encodeURIComponent(projectId)}/verification-profiles`);
export const approveVerificationProfile = (projectId, checksum, body) => net.post(`/api/v2/projects/${encodeURIComponent(projectId)}/verification-profiles/${encodeURIComponent(checksum)}/approve`, body);
export const verifications = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/verifications`);
export const runVerification = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/verifications`, body);
export const verificationEvidence = (id, verificationId, checkId) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/evidence/${encodeURIComponent(verificationId)}/${encodeURIComponent(checkId)}`);
export const completeTask = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/complete`, body);
export const repairTask = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/repair`, body);
export const workspacePreflight = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/workspace-preflight`);
export const workspaces = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/workspaces`);
export const createWorkspace = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/workspaces`, body);
export const checkpoints = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/checkpoints`);
export const createCheckpoint = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/checkpoints`, body);
export const previewRecovery = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/recovery-previews`, body);
export const executeRecovery = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/recovery-executions`, body);
export const forkTask = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/forks`, body);
export const questions = (id) => net.get(`/api/v2/tasks/${encodeURIComponent(id)}/questions`);
export const answerQuestion = (id, questionId, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/questions/${encodeURIComponent(questionId)}/answer`, body);
export const stopRun = (id, runId, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/runs/${encodeURIComponent(runId)}/stop`, body);
export const steerRun = (id, runId, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/runs/${encodeURIComponent(runId)}/steer`, body);
export const cancelTask = (id, body) => net.post(`/api/v2/tasks/${encodeURIComponent(id)}/cancel`, body);
export const controlQueue = (itemId, action, body) => net.post(`/api/v2/queue/${encodeURIComponent(itemId)}/${encodeURIComponent(action)}`, body);
export const previewSession = (sid) => net.get(`/api/v2/sessions/${encodeURIComponent(sid)}/task-preview`);
export const importSession = (sid, projectId) => net.post(`/api/v2/sessions/${encodeURIComponent(sid)}/import-task`, { project_id: projectId });
export const projectMemories = (projectId, status = "") => net.get(`/api/v2/projects/${encodeURIComponent(projectId)}/memories${status ? `?status=${encodeURIComponent(status)}` : ""}`);
export const memorySource = (projectId, sourceRef) => net.get(`/api/v2/projects/${encodeURIComponent(projectId)}/memory-sources?source_ref=${encodeURIComponent(sourceRef)}`);
export const memoryReceipts = (projectId) => net.get(`/api/v2/projects/${encodeURIComponent(projectId)}/memory-usage-receipts`);
export const reviewMemory = (projectId, memoryId, action, body) => net.post(`/api/v2/projects/${encodeURIComponent(projectId)}/memories/${encodeURIComponent(memoryId)}/${action}`, body);
export const bindSessionProject = (projectId) => net.post("/api/v2/session/project", { project_id: projectId || null });
export const privacy = () => net.get("/api/v2/privacy");
export const setPrivacy = (body) => net.post("/api/v2/privacy", body);
export const previewDiagnostics = (body = {}) => net.post("/api/v2/diagnostics/preview", body);
export const exportDiagnostics = (previewId) => net.post("/api/v2/diagnostics/export", { preview_id: previewId });
export const betaObservability = () => net.get("/api/v2/beta-observability");
