import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(packageRoot, 'src/client/index.ts')
const contractSource = resolve(packageRoot, '../runtime-contract/src/index.ts')
const outputPath = resolve(packageRoot, 'lib/client.js')

// Bundle the pure Product contract helpers into this closed Client row. DSH's
// browser ModuleLoader must not depend on an unregistered Node package row.
const result = await build({
  entryPoints: [sourcePath],
  bundle: true,
  write: false,
  platform: 'browser',
  format: 'cjs',
  target: 'es2022',
  logLevel: 'silent',
  plugins: [{
    name: 'xiaoshe-runtime-contract-source',
    setup(buildApi) {
      buildApi.onResolve({ filter: /^@xiaoshe\/runtime-contract$/ }, () => ({ path: contractSource }))
    },
  }],
})
const body = result.outputFiles[0]?.text
if (body === undefined) throw new Error('runtime DSH provider Client build produced no artifact')
const indented = body.split('\n').map(line => `    ${line}`).join('\n')

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `// Generated by @xiaoshe/runtime-dsh-provider.\nwindow.__ModuleLoader__.load({\n  id: '@xiaoshe/runtime-dsh-provider',\n  factory: (require) => {\n    var module = { exports: {} }\n    var exports = module.exports\n${indented}\n    return module.exports\n  },\n})\n`, 'utf8')
